### ISSUE TITLE
Changes in 1.2 break reading metadata

### ISSUE THREAD

**Issue by pakoito** [Takhion/kotlin-metadata#1]
As reported here:

https://github.com/arrow-kt/arrow/issues/586#issue-290199905

**Comment by Takhion** [comment]
Fixed by https://github.com/Takhion/kotlin-metadata/commit/437cabe38085aeb1f9bcdd8cc05f37b29701d7d3 in [`1.2.1`](https://github.com/Takhion/kotlin-metadata/releases/tag/1.2.1)
