### ISSUE TITLE
Can't access `processingEnv` from processor class.

### ISSUE THREAD

**Issue by rharter** [Takhion/kotlin-metadata#4]
When making your processor extend `KotlinAbstractProcessor` and implement `KotlinMetadataUtils`, you cannot access the `processingEnv` because of the conflicting definitions in `KotlinAbstractProcessor` and `KotlingProcessingEnvironment`, from which `KotlinMetadataUtils` is a descendant. 

The best I could come up with to work around this is to cast `this` as `KotlinAbstractProcessor` so the compiler knows which one to access.

**Comment by Takhion** [comment]
Hey @rharter!
Don't worry, I already rewrote the `KotlinAbstractProcessor` part and made sure there are no conflicts, you'll get it in the next version 😉

**Comment by rharter** [comment]
🎉  WOOT WOOT 🎉

Nice work!
