### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by swankjesse** [Takhion/kotlin-metadata#5]
So we can depend on it in Moshi!
https://github.com/square/moshi/pull/435/files

**Comment by LouisCAD** [comment]
@swankjesse Couldn't it be released on jcenter instead? If not, I'm curious to learn the reasons.

**Comment by Shakeskeyboarde** [comment]
It is released in jcenter... https://bintray.com/takhion/maven/kotlin-metadata

**Comment by swankjesse** [comment]
My understanding is that libraries published to Maven Central (such as Moshi) need to have their dependencies on Maven Central.

**Comment by LouisCAD** [comment]
@Takhion bintray can sync to maven central. This is what kotshi does according to [its `RELEASING.md` guide](https://github.com/ansman/kotshi/blob/master/RELEASING.md). This could be your solution.

**Comment by Takhion** [comment]
Fixed in [`v1.3.0`](https://github.com/Takhion/kotlin-metadata/releases/tag/v1.3.0) 🎉

**Comment by ZacSweers** [comment]
Thanks! https://github.com/square/moshi/pull/474
